### ISSUE TITLE
[질문] efriend_api.type.ts 는 어떻게 생성하는 걸가요?

### ISSUE THREAD

**Issue by jinsankim** [pnuskgh/EFriendExpert#33]
좋은 Open Source 만들어 주셔서 고맙습니다.

개인적인 궁금증이 있는데요. efriend_api.type.ts 는 어떻게 생성하는 걸가요?

`trid.constant.ts`를 이용하는 것 같긴 한데, 방법을 모르겠네요.

관련 command 또는 참고할 만한 file/line 조언 주시면 고맙겠습니다.

감사합니다.

**Comment by pnuskgh** [comment]
KIS Developers API 문서를 기반으로 생성 됩니다.
https://apiportal.koreainvestment.com/apiservice/oauth2#L_5c87ba63-740a-4166-93ac-803510bb9c02
